import {getSession,onAuthStateChange,signUp,signIn,signOut,sendPasswordReset,updatePassword} from './auth.js';
import {DEFAULT_FAILURE_COUNTS,loadSettings,saveSettings,loadActiveWorkout,saveActiveWorkout,insertBodyWeight,loadBodyWeights,loadWorkoutHistory,saveCompletedWorkout,deleteAllUserData,localDate,ensureDefaultExerciseConfig,loadExerciseConfig,saveExerciseConfig} from './database.js';
import {renderChart,renderHistory,downloadCsv,formatWeight} from './reports.js';

let session=null,settings=null,exerciseConfig=[],activeWorkout=null,history=[],bodyWeights=[],reportReturn='workoutScreen',settingsReturn='workoutScreen',recoveryMode=false,restTimerInterval=null;
const $=id=>document.getElementById(id),screens=['authScreen','passwordScreen','setupScreen','workoutScreen','completionScreen','reportScreen','settingsScreen'];
const hideScreens=()=>screens.forEach(id=>$(id).classList.add('hidden'));
function showStatus(message,error=false){const b=$('statusMessage');b.textContent=message;b.classList.remove('hidden','error');if(error)b.classList.add('error');}
function clearStatus(){$('statusMessage').classList.add('hidden');}
function busy(button,on,text='Working...'){button.disabled=on;if(on){button.dataset.old=button.textContent;button.textContent=text}else button.textContent=button.dataset.old||button.textContent;}

$('signInButton').addEventListener('click',async()=>authAction($('signInButton'),()=>signIn($('authEmail').value.trim(),$('authPassword').value),'Signing In...'));
$('signUpButton').addEventListener('click',async()=>authAction($('signUpButton'),async()=>{const d=await signUp($('authEmail').value.trim(),$('authPassword').value);if(!d.session)showStatus('Account created. Check your email and tap the confirmation link.');return d;},'Creating...'));
$('forgotPasswordButton').addEventListener('click',async()=>{const email=$('authEmail').value.trim();if(!email)return showStatus('Enter your email address first.',true);try{await sendPasswordReset(email);showStatus('Password reset email sent.');}catch(e){showStatus(e.message,true);}});
$('signOutButton').addEventListener('click',signOut);$('saveNewPassword').addEventListener('click',async()=>{const p=$('newPassword').value;if(p.length<6)return showStatus('Password must be at least 6 characters.',true);try{await updatePassword(p);recoveryMode=false;await route();}catch(e){showStatus(e.message,true);}});
$('saveSetup').addEventListener('click',saveSetup);$('finishWorkout').addEventListener('click',finishWorkout);$('advanceWorkout').addEventListener('click',async()=>{if(confirm(`Start ${settings.next_workout} Day now?`)){await saveSettings(session.user.id,{last_completed_workout_date:null});settings.last_completed_workout_date=null;await showWorkout();}});
document.querySelectorAll('.report-button').forEach(b=>b.addEventListener('click',()=>showReport(b.closest('section').id)));$('closeReport').addEventListener('click',()=>{hideScreens();$(reportReturn).classList.remove('hidden');});$('reportMetric').addEventListener('change',drawReport);$('downloadCsv').addEventListener('click',()=>downloadCsv(history,exerciseMap()));$('updateBodyWeight').addEventListener('click',updateBodyWeight);
$('headerSettingsButton').addEventListener('click',()=>showSettings(currentVisibleScreen()));$('addExerciseButton').addEventListener('click',addExerciseCard);$('saveSettingsButton').addEventListener('click',saveAllExerciseSettings);$('closeSettingsButton').addEventListener('click',()=>{hideScreens();$(settingsReturn).classList.remove('hidden');});$('resetApp').addEventListener('click',resetData);

async function authAction(button,action,label){clearStatus();const email=$('authEmail').value.trim(),pass=$('authPassword').value;if(!email||pass.length<6)return showStatus('Enter a valid email and a password of at least 6 characters.',true);busy(button,true,label);try{await action();}catch(e){showStatus(e.message,true)}finally{busy(button,false)}}
onAuthStateChange(async(event,newSession)=>{session=newSession;if(event==='PASSWORD_RECOVERY'){recoveryMode=true;hideScreens();$('passwordScreen').classList.remove('hidden');return;}await route();});

async function route(){clearStatus();hideScreens();session=session||(await getSession());$('appHeader').classList.toggle('hidden',!session);if(!session){$('authScreen').classList.remove('hidden');return;}$('userEmail').textContent=session.user.email||'';if(recoveryMode){$('passwordScreen').classList.remove('hidden');return;}try{showStatus('Loading your fitness data...');settings=await loadSettings(session.user.id);if(!settings.weights||Object.keys(settings.weights).length===0){clearStatus();$('setupScreen').classList.remove('hidden');return;}exerciseConfig=await ensureDefaultExerciseConfig(session.user.id,settings);history=await loadWorkoutHistory(session.user.id);bodyWeights=await loadBodyWeights(session.user.id);clearStatus();if(settings.workout_count>0&&settings.workout_count%18===0){const lw=history.at(-1),lb=bodyWeights.at(-1);if((lb?new Date(lb.recorded_at).getTime():0)<=(lw?new Date(lw.completed_at).getTime():0))await promptBodyWeight('18_workouts');}if(settings.last_completed_workout_date===localDate())showCompletion();else await showWorkout();}catch(e){showStatus(`Could not load the app: ${e.message}`,true);}}

async function saveSetup(){const bw=Number($('bodyWeight').value),weights={squat:Number($('squat').value),overheadPress:Number($('overheadPress').value),barbellRow:Number($('barbellRow').value),benchPress:Number($('benchPress').value),deadlift:Number($('deadlift').value)};if(!Number.isFinite(bw)||bw<=0)return alert('Enter a valid body weight.');if(!Object.values(weights).every(v=>Number.isFinite(v)&&v>0))return alert('Enter a positive starting weight for every exercise.');if(!confirm(`Save body weight ${formatWeight(bw)} lb and these starting lift weights?`))return;await saveSettings(session.user.id,{current_body_weight:bw,workout_count:0,next_workout:'A',weights,failure_counts:DEFAULT_FAILURE_COUNTS,last_completed_workout_date:null});await insertBodyWeight(session.user.id,bw,'initial');settings=await loadSettings(session.user.id);exerciseConfig=await ensureDefaultExerciseConfig(session.user.id,settings);await route();}

function dayExercises(day){return exerciseConfig.filter(e=>e.active&&e.templates.some(t=>t.workout_day===day)).sort((a,b)=>(a.templates.find(t=>t.workout_day===day)?.sort_order??0)-(b.templates.find(t=>t.workout_day===day)?.sort_order??0));}
async function showWorkout(){
 hideScreens();$('workoutScreen').classList.remove('hidden');
 const day=settings.next_workout||'A',items=dayExercises(day);$('workoutTitle').textContent=`${day} Day`;
 if(!items.length){$('exerciseList').innerHTML='<p>No exercises are assigned to this day. Open Settings to add one.</p>';updateRestTimerDisplay(Number(settings.rest_seconds??60));return;}
 const cloud=await loadActiveWorkout(session.user.id);
 if(cloud&&cloud.workout_day===day&&cloud.workout_state?.version===4)activeWorkout=cloud.workout_state;
 else{
  activeWorkout={version:4,day,startedDate:localDate(),restTimerEnd:null,items:{}};
  items.forEach(e=>{
   const t=e.templates.find(x=>x.workout_day===day),warmupSets=[];
   (e.warmups||[]).forEach(w=>{const weight=roundToIncrement(Number(e.current_weight)*(Number(w.weight_percentage)/100),Number(e.weight_increment));for(let n=0;n<Number(w.warmup_sets);n++)warmupSets.push({status:'ready',reps:Number(w.warmup_reps),percentage:Number(w.weight_percentage),weight});});
   activeWorkout.items[e.id]={exerciseId:e.id,exerciseKey:e.exercise_key,exerciseName:e.name,workingWeight:Number(e.current_weight),increment:Number(e.weight_increment),sets:Number(t.working_sets),reps:Number(t.target_reps),warmupSets,workingSets:Array.from({length:Number(t.working_sets)},()=>({status:'ready',currentReps:Number(t.target_reps)}))};
  });
  await saveActiveWorkout(session.user.id,day,activeWorkout);
 }
 renderWorkout();resumeRestTimer();
}
function roundToIncrement(value,increment){return Math.round(value/increment)*increment;}
function configuredRestSeconds(){const value=Number(settings?.rest_seconds??60);return Number.isFinite(value)?Math.max(0,Math.min(600,Math.round(value))):60;}
function updateRestTimerDisplay(seconds){$('restTimer').textContent=`REST: ${Math.max(0,Math.ceil(seconds))}s`;}
function stopRestTimer(){if(restTimerInterval){clearInterval(restTimerInterval);restTimerInterval=null;}}
function resumeRestTimer(){stopRestTimer();const configured=configuredRestSeconds();if(!activeWorkout?.restTimerEnd){updateRestTimerDisplay(configured);return;}const tick=()=>{const remaining=Math.max(0,Math.ceil((new Date(activeWorkout.restTimerEnd).getTime()-Date.now())/1000));updateRestTimerDisplay(remaining);if(remaining<=0){stopRestTimer();activeWorkout.restTimerEnd=null;saveActiveWorkout(session.user.id,activeWorkout.day,activeWorkout).catch(()=>{});}};tick();if(activeWorkout.restTimerEnd)restTimerInterval=setInterval(tick,250);}
async function startRestTimer(){const seconds=configuredRestSeconds();stopRestTimer();activeWorkout.restTimerEnd=seconds>0?new Date(Date.now()+seconds*1000).toISOString():null;updateRestTimerDisplay(seconds);await saveActiveWorkout(session.user.id,activeWorkout.day,activeWorkout);if(seconds>0)resumeRestTimer();}

function renderWorkout(){
 const list=$('exerciseList');list.innerHTML='';
 dayExercises(activeWorkout.day).forEach(ex=>{
  const item=activeWorkout.items[ex.id];if(!item)return;
  const card=document.createElement('div');card.className='exercise-card';
  card.innerHTML=`<div class="exercise-header"><span>${escapeHtml(ex.name)}</span><button class="exercise-weight-button" type="button">${formatWeight(item.workingWeight)} lbs</button></div>${item.warmupSets?.length?'<div class="warmup-block"><div class="warmup-title">Warmup</div><div class="warmup-set-list"></div></div>':''}<div class="set-list"></div>`;
  card.querySelector('.exercise-weight-button').addEventListener('click',()=>changeWeight(ex,item,card.querySelector('.exercise-weight-button')));
  const warmList=card.querySelector('.warmup-set-list');
  (item.warmupSets||[]).forEach(state=>{
   const b=document.createElement('button');b.type='button';b.className=`warmup-button ${state.status==='completed'?'completed':''}`;
   b.innerHTML=`<span>${formatWeight(state.reps)} reps at ${formatWeight(state.percentage)}%</span><span class="warmup-weight">${formatWeight(state.weight)} lb</span>`;
   b.addEventListener('click',async()=>{const completedNow=state.status!=='completed';state.status=completedNow?'completed':'ready';b.classList.toggle('completed',completedNow);if(completedNow)await startRestTimer();else await saveActiveWorkout(session.user.id,activeWorkout.day,activeWorkout);});
   warmList.append(b);
  });
  const setList=card.querySelector('.set-list');
  item.workingSets.forEach(state=>{
   const b=document.createElement('button');b.type='button';b.className=`rep-button ${state.status==='completed'?'completed':state.status==='failed'?'failed':''}`;b.textContent=state.currentReps;
   b.addEventListener('click',async()=>{let completedNow=false;if(state.status==='ready'){state.status='completed';completedNow=true;}else if(state.status==='completed'){state.status='failed';state.currentReps=item.reps-1;}else if(state.currentReps>0)state.currentReps--;else{state.status='ready';state.currentReps=item.reps;}b.className=`rep-button ${state.status==='completed'?'completed':state.status==='failed'?'failed':''}`;b.textContent=state.currentReps;if(completedNow)await startRestTimer();else await saveActiveWorkout(session.user.id,activeWorkout.day,activeWorkout);});
   setList.append(b);
  });
  list.append(card);
 });
}
async function changeWeight(ex,item,button){const raw=prompt(`Enter the new weight for ${ex.name}.`,item.workingWeight);if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<=0)return alert('Enter a positive weight.');if(!confirm(`Permanently change ${ex.name} from ${formatWeight(item.workingWeight)} lb to ${formatWeight(value)} lb?`))return;item.workingWeight=value;ex.current_weight=value;(item.warmupSets||[]).forEach(w=>{w.weight=roundToIncrement(value*(Number(w.percentage)/100),Number(ex.weight_increment));});await saveExerciseConfig(session.user.id,configForSave());exerciseConfig=await loadExerciseConfig(session.user.id);await saveActiveWorkout(session.user.id,activeWorkout.day,activeWorkout);button.textContent=`${formatWeight(value)} lbs`;renderWorkout();}

async function finishWorkout(){const items=Object.values(activeWorkout.items);if(!items.every(i=>(i.warmupSets||[]).every(s=>s.status==='completed')))return alert('Complete every configured warmup set before finishing.');if(!items.every(i=>i.workingSets.every(s=>s.status!=='ready')))return alert('Record every working set before finishing.');if(!confirm('Finish and permanently save this workout?'))return;const results=[],updates=[],lines=[];for(const item of items){const ex=exerciseConfig.find(e=>e.id===item.exerciseId),success=item.workingSets.every(s=>s.status==='completed');let failure=Number(ex.failure_count||0),next=item.workingWeight;if(success){next=item.workingWeight+Number(ex.weight_increment);failure=0;lines.push(`${ex.name} completed. Next weight: ${formatWeight(next)} lb.`);}else{failure++;if(failure>=2){next=roundToIncrement(item.workingWeight*.9,Number(ex.weight_increment));failure=0;lines.push(`${ex.name} missed twice. Next weight reduced to ${formatWeight(next)} lb.`);}else lines.push(`${ex.name} not completed. Next weight remains ${formatWeight(next)} lb.`);}results.push({exerciseId:ex.id,exerciseKey:ex.exercise_key,exerciseName:ex.name,performedWeight:item.workingWeight,prescribedSets:item.sets,prescribedReps:item.reps,actualReps:item.workingSets.map(s=>Number(s.currentReps)),completed:success,nextWeight:next,failureCountAfter:failure,increment:Number(ex.weight_increment)});updates.push({id:ex.id,currentWeight:next,failureCount:failure});ex.current_weight=next;ex.failure_count=failure;}const number=Number(settings.workout_count||0)+1,nextDay=activeWorkout.day==='A'?'B':'A';await saveCompletedWorkout({userId:session.user.id,workoutNumber:number,workoutDate:localDate(),workoutDay:activeWorkout.day,bodyWeight:Number(settings.current_body_weight),exerciseResults:results,exerciseUpdates:updates,settingsChanges:{current_body_weight:settings.current_body_weight,workout_count:number,next_workout:nextDay,weights:settings.weights||{},failure_counts:settings.failure_counts||{},last_completed_workout_date:localDate()}});settings={...settings,workout_count:number,next_workout:nextDay,last_completed_workout_date:localDate()};sessionStorage.setItem('lastSummary',JSON.stringify(lines));if(number%18===0)await promptBodyWeight('18_workouts');showCompletion();}
function showCompletion(){stopRestTimer();hideScreens();$('completionScreen').classList.remove('hidden');$('nextWorkoutMessage').textContent=`${settings.next_workout} Day is next. Start it now or it will open automatically on a later day.`;$('advanceWorkout').textContent=`Start ${settings.next_workout} Day`;const box=$('completionSummary');box.innerHTML='';JSON.parse(sessionStorage.getItem('lastSummary')||'[]').forEach(line=>{const d=document.createElement('div');d.className='summary-line';d.textContent=line;box.append(d);});}
async function promptBodyWeight(reason){const raw=prompt(`You have completed ${settings.workout_count} workouts. Enter your updated body weight.`,settings.current_body_weight);if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<=0)return alert('Body weight was not saved.');if(!confirm(`Save ${formatWeight(value)} lb as your current body weight?`))return;await insertBodyWeight(session.user.id,value,reason);await saveSettings(session.user.id,{current_body_weight:value});settings.current_body_weight=value;bodyWeights=await loadBodyWeights(session.user.id);}
async function updateBodyWeight(){await promptBodyWeight('manual');await showReport('reportScreen');}

function exerciseMap(){return Object.fromEntries(exerciseConfig.flatMap(e=>[[e.id,e.name],[e.exercise_key,e.name]]));}
async function showReport(from){if(from!=='reportScreen')reportReturn=from||'workoutScreen';hideScreens();$('reportScreen').classList.remove('hidden');history=await loadWorkoutHistory(session.user.id);bodyWeights=await loadBodyWeights(session.user.id);$('totalWorkoutCount').textContent=history.length;$('currentBodyWeightDisplay').textContent=`${formatWeight(settings.current_body_weight)} lb`;const select=$('reportMetric'),selected=select.value;select.innerHTML='<option value="bodyWeight">Body Weight</option>'+exerciseConfig.map(e=>`<option value="${e.id}">${escapeHtml(e.name)}</option>`).join('');if([...select.options].some(o=>o.value===selected))select.value=selected;drawReport();renderHistory($('workoutHistoryList'),history,exerciseMap());}
function drawReport(){renderChart($('progressChart'),$('chartMessage'),$('reportMetric').value,history,bodyWeights,exerciseMap());}

function currentVisibleScreen(){return screens.find(id=>!$(id).classList.contains('hidden'))||'workoutScreen';}
function showSettings(from){settingsReturn=from==='settingsScreen'?'workoutScreen':from;hideScreens();$('settingsScreen').classList.remove('hidden');$('restTimerSeconds').value=configuredRestSeconds();renderSettings();}
function renderSettings(){const list=$('settingsExerciseList');list.innerHTML='';exerciseConfig.filter(e=>e.active).forEach((e,i)=>list.append(createSettingsCard(e,i)));}
function createSettingsCard(ex,index){const card=document.createElement('div');card.className='settings-card';card.dataset.id=ex.id||'';card.dataset.key=ex.exercise_key||`custom_${crypto.randomUUID().replaceAll('-','')}`;const dayA=ex.templates?.find(t=>t.workout_day==='A'),dayB=ex.templates?.find(t=>t.workout_day==='B');card.innerHTML=`<div class="settings-card-header"><h2>${escapeHtml(ex.name||'New Exercise')}</h2><button class="small-button remove-button archive-button" type="button">Remove</button></div><div class="settings-grid"><label>Exercise Name<input class="setting-name" value="${escapeAttr(ex.name||'')}"></label><label>Current Weight<input class="setting-weight" type="number" min="0.1" step="0.1" value="${Number(ex.current_weight||5)}"></label><label>Weight Increment<input class="setting-increment" type="number" min="0.1" step="0.1" value="${Number(ex.weight_increment||5)}"></label></div><div class="day-options"><label><input class="day-enabled" data-day="A" type="checkbox" ${dayA?'checked':''}> A Day</label><label><input class="day-enabled" data-day="B" type="checkbox" ${dayB?'checked':''}> B Day</label></div><div class="settings-grid"><label>A Day Sets<input class="day-sets" data-day="A" type="number" min="1" max="50" value="${dayA?.working_sets||5}"></label><label>A Day Reps<input class="day-reps" data-day="A" type="number" min="1" max="100" value="${dayA?.target_reps||5}"></label><label>B Day Sets<input class="day-sets" data-day="B" type="number" min="1" max="50" value="${dayB?.working_sets||5}"></label><label>B Day Reps<input class="day-reps" data-day="B" type="number" min="1" max="100" value="${dayB?.target_reps||5}"></label></div><div class="warmup-editor"><h3>Warmup Routine</h3><div class="warmup-list"></div><button class="small-button add-warmup" type="button">Add Warmup Step</button></div>`;const warmList=card.querySelector('.warmup-list');(ex.warmups||[]).forEach(w=>warmList.append(createWarmupRow(w)));card.querySelector('.add-warmup').addEventListener('click',()=>warmList.append(createWarmupRow({warmup_sets:1,warmup_reps:5,weight_percentage:50})));card.querySelector('.remove-button').addEventListener('click',()=>{if(confirm(`Remove ${card.querySelector('.setting-name').value||'this exercise'} from future workouts? Its old history will remain.`))card.remove();});card.querySelector('.setting-name').addEventListener('input',ev=>card.querySelector('h2').textContent=ev.target.value||'New Exercise');return card;}
function createWarmupRow(w){const row=document.createElement('div');row.className='warmup-step';row.innerHTML=`<label>Sets<input class="warm-sets" type="number" min="1" max="20" value="${Number(w.warmup_sets||w.sets||1)}"></label><label>Reps<input class="warm-reps" type="number" min="1" max="100" value="${Number(w.warmup_reps||w.reps||5)}"></label><label>% Weight<input class="warm-percent" type="number" min="1" max="100" step="0.5" value="${Number(w.weight_percentage||w.percentage||50)}"></label><button class="small-button remove-button" type="button">Remove</button>`;row.querySelector('button').addEventListener('click',()=>row.remove());return row;}
function addExerciseCard(){const ex={id:null,exercise_key:`custom_${crypto.randomUUID().replaceAll('-','')}`,name:'New Exercise',current_weight:5,weight_increment:5,failure_count:0,active:true,templates:[],warmups:[]};$('settingsExerciseList').append(createSettingsCard(ex,exerciseConfig.length));}
function readSettingsCards(){return [...document.querySelectorAll('.settings-card[data-key]')].map((card,index)=>{const value=sel=>card.querySelector(sel).value,num=sel=>Number(value(sel));const dayConfig={};for(const day of ['A','B'])dayConfig[day]={enabled:card.querySelector(`.day-enabled[data-day="${day}"]`).checked,sets:Number(card.querySelector(`.day-sets[data-day="${day}"]`).value),reps:Number(card.querySelector(`.day-reps[data-day="${day}"]`).value),sort_order:index};return{id:card.dataset.id||null,exercise_key:card.dataset.key,name:value('.setting-name').trim(),current_weight:num('.setting-weight'),weight_increment:num('.setting-increment'),failure_count:Number(exerciseConfig.find(e=>e.id===card.dataset.id)?.failure_count||0),active:true,days:dayConfig,warmups:[...card.querySelectorAll('.warmup-step')].map(r=>({sets:Number(r.querySelector('.warm-sets').value),reps:Number(r.querySelector('.warm-reps').value),percentage:Number(r.querySelector('.warm-percent').value)}))};});}
function validateConfig(items){if(!items.length)return 'Add at least one exercise.';for(const item of items){if(!item.name)return 'Every exercise needs a name.';if(!(item.current_weight>0)||!(item.weight_increment>0))return `${item.name}: weight and increment must be greater than zero.`;if(!item.days.A.enabled&&!item.days.B.enabled)return `${item.name}: assign it to A Day, B Day, or both.`;for(const d of ['A','B'])if(item.days[d].enabled&&(!(item.days[d].sets>0)||!(item.days[d].reps>0)))return `${item.name}: sets and reps must be greater than zero.`;for(const w of item.warmups)if(!(w.sets>0)||!(w.reps>0)||!(w.percentage>0&&w.percentage<=100))return `${item.name}: warmup values are invalid.`;}return null;}
function configForSave(){return exerciseConfig.map((e,i)=>({id:e.id,exercise_key:e.exercise_key,name:e.name,current_weight:e.current_weight,weight_increment:e.weight_increment,failure_count:e.failure_count,active:e.active,days:{A:{enabled:!!e.templates.find(t=>t.workout_day==='A'),sets:e.templates.find(t=>t.workout_day==='A')?.working_sets||5,reps:e.templates.find(t=>t.workout_day==='A')?.target_reps||5,sort_order:i},B:{enabled:!!e.templates.find(t=>t.workout_day==='B'),sets:e.templates.find(t=>t.workout_day==='B')?.working_sets||5,reps:e.templates.find(t=>t.workout_day==='B')?.target_reps||5,sort_order:i}},warmups:e.warmups.map(w=>({sets:w.warmup_sets,reps:w.warmup_reps,percentage:w.weight_percentage}))}));}
async function saveAllExerciseSettings(){const items=readSettingsCards(),error=validateConfig(items),restSeconds=Number($('restTimerSeconds').value);if(error)return alert(error);if(!Number.isInteger(restSeconds)||restSeconds<0||restSeconds>600)return alert('Rest timer must be a whole number from 0 to 600 seconds.');if(!confirm('Save the rest timer, exercise, progression, set, rep, and warmup settings?'))return;try{showStatus('Saving settings...');exerciseConfig=await saveExerciseConfig(session.user.id,items);settings=await saveSettings(session.user.id,{rest_seconds:restSeconds});await saveActiveWorkout(session.user.id,settings.next_workout,{version:0});clearStatus();alert('Settings saved. Your next workout will use the new configuration.');showSettings(settingsReturn);}catch(e){showStatus(`Could not save settings: ${e.message}`,true);}}
async function resetData(){if(!confirm('Open reset options? Nothing will be erased yet.'))return;if(prompt('Type RESET to permanently erase your cloud fitness data.')!=='RESET')return alert('Nothing was erased.');if(!confirm('Final warning: erase all cloud workout, body-weight, and exercise configuration data?'))return;await deleteAllUserData(session.user.id);await route();}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function escapeAttr(v){return escapeHtml(v);}
route();
