import { getSession, onAuthStateChange, signUp, signIn, signOut, sendPasswordReset, updatePassword } from './auth.js';
import { DEFAULT_FAILURE_COUNTS, loadSettings, saveSettings, loadActiveWorkout, saveActiveWorkout, insertBodyWeight, loadBodyWeights, loadWorkoutHistory, saveCompletedWorkout, migrateLocalData, deleteAllUserData, localDate } from './database.js';
import { exerciseNames, renderChart, renderHistory, downloadCsv, formatWeight } from './reports.js';

const workouts={A:[['squat',5,5],['overheadPress',5,5],['barbellRow',5,5]],B:[['squat',5,5],['benchPress',5,5],['deadlift',5,1]]};
let session=null,settings=null,activeWorkout=null,history=[],bodyWeights=[],reportReturn='workoutScreen',recoveryMode=false;
const $=(id)=>document.getElementById(id);
const screens=['authScreen','passwordScreen','setupScreen','workoutScreen','completionScreen','reportScreen'];
function hideScreens(){screens.forEach((id)=>$(id).classList.add('hidden'));}
function showStatus(message,error=false){const box=$('statusMessage');box.textContent=message;box.classList.remove('hidden','error');if(error)box.classList.add('error');}
function clearStatus(){$('statusMessage').classList.add('hidden');}
function busy(button,on,text='Working...'){button.disabled=on;if(on){button.dataset.old=button.textContent;button.textContent=text}else button.textContent=button.dataset.old||button.textContent;}

$('signInButton').addEventListener('click',async()=>{await authAction($('signInButton'),()=>signIn($('authEmail').value.trim(),$('authPassword').value),'Signing In...');});
$('signUpButton').addEventListener('click',async()=>{await authAction($('signUpButton'),async()=>{const data=await signUp($('authEmail').value.trim(),$('authPassword').value);if(!data.session)showStatus('Account created. Check your email and tap the confirmation link.');return data;},'Creating...');});
$('forgotPasswordButton').addEventListener('click',async()=>{const email=$('authEmail').value.trim();if(!email)return showStatus('Enter your email address first.',true);try{await sendPasswordReset(email);showStatus('Password reset email sent.');}catch(e){showStatus(e.message,true);}});
$('signOutButton').addEventListener('click',async()=>{await signOut();});
$('saveNewPassword').addEventListener('click',async()=>{const p=$('newPassword').value;if(p.length<6)return showStatus('Password must be at least 6 characters.',true);try{await updatePassword(p);recoveryMode=false;showStatus('Password updated.');await route();}catch(e){showStatus(e.message,true);}});
$('saveSetup').addEventListener('click',saveSetup);
$('finishWorkout').addEventListener('click',finishWorkout);
$('advanceWorkout').addEventListener('click',async()=>{if(confirm(`Start ${settings.next_workout} Day now?`)){await saveSettings(session.user.id,{last_completed_workout_date:null});settings.last_completed_workout_date=null;await showWorkout();}});
document.querySelectorAll('.report-button').forEach((b)=>b.addEventListener('click',()=>showReport(b.closest('section').id)));
$('closeReport').addEventListener('click',()=>{hideScreens();$(reportReturn).classList.remove('hidden');});
$('reportMetric').addEventListener('change',drawReport);
$('downloadCsv').addEventListener('click',()=>downloadCsv(history));
$('updateBodyWeight').addEventListener('click',updateBodyWeight);
$('settingsButton').addEventListener('click',resetData);

async function authAction(button,action,label){clearStatus();const email=$('authEmail').value.trim(),pass=$('authPassword').value;if(!email||pass.length<6)return showStatus('Enter a valid email and a password of at least 6 characters.',true);busy(button,true,label);try{await action();}catch(e){showStatus(e.message,true)}finally{busy(button,false)}}

onAuthStateChange(async(event,newSession)=>{session=newSession;if(event==='PASSWORD_RECOVERY'){recoveryMode=true;hideScreens();$('passwordScreen').classList.remove('hidden');return;}await route();});

async function route(){clearStatus();hideScreens();session=session||(await getSession());$('appHeader').classList.toggle('hidden',!session);if(!session){$('authScreen').classList.remove('hidden');return;}$('userEmail').textContent=session.user.email||'';if(recoveryMode){$('passwordScreen').classList.remove('hidden');return;}try{showStatus('Loading your fitness data...');settings=await loadSettings(session.user.id);await offerMigration();settings=await loadSettings(session.user.id);clearStatus();if(!settings.weights||Object.keys(settings.weights).length===0){$('setupScreen').classList.remove('hidden');return;}history=await loadWorkoutHistory(session.user.id);bodyWeights=await loadBodyWeights(session.user.id);if(settings.workout_count>0&&settings.workout_count%18===0){const latestWorkout=history.at(-1);const latestBodyWeight=bodyWeights.at(-1);const workoutTime=latestWorkout?new Date(latestWorkout.completed_at).getTime():0;const bodyWeightTime=latestBodyWeight?new Date(latestBodyWeight.recorded_at).getTime():0;if(bodyWeightTime<=workoutTime){await promptBodyWeight('18_workouts');}}
if(settings.last_completed_workout_date===localDate()){showCompletion();}else await showWorkout();}catch(e){showStatus(`Could not load the app: ${e.message}`,true);}}

async function offerMigration(){const local=readLocalData();if(!local.weights||Object.keys(local.weights).length===0)return;if(settings.weights&&Object.keys(settings.weights).length)return;const ok=confirm('Existing workout data was found on this device. Move it into your cloud account now?');if(!ok)return;showStatus('Moving your existing records to the cloud...');await migrateLocalData(session.user.id,local);localStorage.setItem('fitnessTrackerCloudMigrationComplete','true');}
function readLocalData(){const parse=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};return{weights:parse('fitnessTrackerWeights',{}),failureCounts:parse('fitnessTrackerFailureCounts',DEFAULT_FAILURE_COUNTS),currentBodyWeight:Number(localStorage.getItem('fitnessTrackerCurrentBodyWeight'))||null,bodyWeightHistory:parse('fitnessTrackerBodyWeightHistory',[]),workoutHistory:parse('fitnessTrackerWorkoutHistory',[]),nextWorkout:localStorage.getItem('nextWorkout')||'A',lastWorkoutDate:localStorage.getItem('lastWorkoutDate'),activeWorkout:parse('activeWorkout',null)};}

async function saveSetup(){const bw=Number($('bodyWeight').value);const weights={squat:Number($('squat').value),overheadPress:Number($('overheadPress').value),barbellRow:Number($('barbellRow').value),benchPress:Number($('benchPress').value),deadlift:Number($('deadlift').value)};if(!Number.isFinite(bw)||bw<=0)return alert('Enter a valid body weight.');if(!Object.values(weights).every((v)=>v>0&&v%5===0))return alert('Every lifting weight must be a positive increment of 5 pounds.');if(!confirm(`Save body weight ${formatWeight(bw)} lb and these starting lift weights?`))return;await saveSettings(session.user.id,{current_body_weight:bw,workout_count:0,next_workout:'A',weights,failure_counts:DEFAULT_FAILURE_COUNTS,last_completed_workout_date:null});await insertBodyWeight(session.user.id,bw,'initial');await route();}

async function showWorkout(){hideScreens();$('workoutScreen').classList.remove('hidden');const day=settings.next_workout||'A';$('workoutTitle').textContent=`${day} Day`;const cloudActive=await loadActiveWorkout(session.user.id);if(cloudActive&&cloudActive.workout_day===day)activeWorkout=cloudActive.workout_state;else{activeWorkout={day,startedDate:localDate(),exerciseWeights:{},exercises:{}};workouts[day].forEach(([key,sets,reps])=>{activeWorkout.exerciseWeights[key]=Number(settings.weights[key]);activeWorkout.exercises[key]=Array.from({length:sets},()=>({status:'ready',currentReps:reps}));});await saveActiveWorkout(session.user.id,day,activeWorkout);}renderWorkout();}
function renderWorkout(){const list=$('exerciseList');list.innerHTML='';workouts[activeWorkout.day].forEach(([key,sets,reps])=>{const card=document.createElement('div');card.className='exercise-card';card.innerHTML=`<div class="exercise-header"><span>${exerciseNames[key]}</span><button class="exercise-weight-button" type="button">${formatWeight(activeWorkout.exerciseWeights[key])} lbs</button></div><div class="set-list"></div>`;card.querySelector('.exercise-weight-button').addEventListener('click',()=>changeWeight(key,card.querySelector('.exercise-weight-button')));const setList=card.querySelector('.set-list');for(let i=0;i<sets;i++){const state=activeWorkout.exercises[key][i];const b=document.createElement('button');b.type='button';b.className=`rep-button ${state.status==='completed'?'completed':state.status==='failed'?'failed':''}`;b.textContent=state.currentReps;b.addEventListener('click',async()=>{if(state.status==='ready')state.status='completed';else if(state.status==='completed'){state.status='failed';state.currentReps=reps-1;}else if(state.currentReps>0)state.currentReps--;else{state.status='ready';state.currentReps=reps;}b.className=`rep-button ${state.status==='completed'?'completed':state.status==='failed'?'failed':''}`;b.textContent=state.currentReps;await saveActiveWorkout(session.user.id,activeWorkout.day,activeWorkout);});setList.append(b);}list.append(card);});}
async function changeWeight(key,button){const old=Number(activeWorkout.exerciseWeights[key]);const raw=prompt(`Enter the new weight for ${exerciseNames[key]}.`,old);if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<=0||value%5!==0)return alert('Weight must be a positive increment of 5 pounds.');if(value===old)return;if(!confirm(`Permanently change ${exerciseNames[key]} from ${old} lb to ${value} lb?`))return;activeWorkout.exerciseWeights[key]=value;settings.weights={...settings.weights,[key]:value};await saveSettings(session.user.id,{weights:settings.weights});await saveActiveWorkout(session.user.id,activeWorkout.day,activeWorkout);button.textContent=`${value} lbs`;}

async function finishWorkout(){const complete=workouts[activeWorkout.day].every(([key])=>activeWorkout.exercises[key].every((s)=>s.status!=='ready'));if(!complete)return alert('Record every set before finishing.');if(!confirm('Finish and permanently save this workout?'))return;const weights={...settings.weights},failures={...DEFAULT_FAILURE_COUNTS,...settings.failure_counts},results=[],lines=[];workouts[activeWorkout.day].forEach(([key,sets,reps])=>{const states=activeWorkout.exercises[key],performed=Number(activeWorkout.exerciseWeights[key]),success=states.every((s)=>s.status==='completed');let next=performed;if(success){next=performed+5;failures[key]=0;lines.push(`${exerciseNames[key]} completed. Next weight: ${next} lb.`);}else{failures[key]=(failures[key]||0)+1;if(failures[key]>=2){next=Math.max(5,Math.round(performed*.9/5)*5);failures[key]=0;lines.push(`${exerciseNames[key]} missed twice. Next weight reduced to ${next} lb.`);}else lines.push(`${exerciseNames[key]} not completed. Next weight remains ${next} lb.`);}weights[key]=next;results.push({exercise:key,performedWeight:performed,prescribedSets:sets,prescribedReps:reps,actualReps:states.map((s)=>Number(s.currentReps)),completed:success,nextWeight:next,failureCountAfter:failures[key]});});const number=Number(settings.workout_count||0)+1,nextDay=activeWorkout.day==='A'?'B':'A';await saveCompletedWorkout({userId:session.user.id,workoutNumber:number,workoutDate:localDate(),workoutDay:activeWorkout.day,bodyWeight:Number(settings.current_body_weight),exerciseResults:results,settingsChanges:{current_body_weight:settings.current_body_weight,workout_count:number,next_workout:nextDay,weights,failure_counts:failures,last_completed_workout_date:localDate()}});settings={...settings,workout_count:number,next_workout:nextDay,weights,failure_counts:failures,last_completed_workout_date:localDate()};sessionStorage.setItem('lastSummary',JSON.stringify(lines));if(number%18===0)await promptBodyWeight('18_workouts');showCompletion();}
function showCompletion(){hideScreens();$('completionScreen').classList.remove('hidden');$('nextWorkoutMessage').textContent=`${settings.next_workout} Day is next. Start it now or it will open automatically on a later day.`;$('advanceWorkout').textContent=`Start ${settings.next_workout} Day`;const box=$('completionSummary');box.innerHTML='';const lines=JSON.parse(sessionStorage.getItem('lastSummary')||'[]');lines.forEach((line)=>{const d=document.createElement('div');d.className='summary-line';d.textContent=line;box.append(d);});}
async function promptBodyWeight(reason){const raw=prompt(`You have completed ${settings.workout_count} workouts. Enter your updated body weight.`,settings.current_body_weight);if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<=0)return alert('Body weight was not saved.');if(!confirm(`Save ${formatWeight(value)} lb as your current body weight?`))return;await insertBodyWeight(session.user.id,value,reason);await saveSettings(session.user.id,{current_body_weight:value});settings.current_body_weight=value;bodyWeights=await loadBodyWeights(session.user.id);}
async function updateBodyWeight(){await promptBodyWeight('manual');await showReport('reportScreen');}

async function showReport(from){if(from!=='reportScreen')reportReturn=from||'workoutScreen';hideScreens();$('reportScreen').classList.remove('hidden');showStatus('Loading report...');history=await loadWorkoutHistory(session.user.id);bodyWeights=await loadBodyWeights(session.user.id);clearStatus();$('totalWorkoutCount').textContent=history.length;$('currentBodyWeightDisplay').textContent=`${formatWeight(settings.current_body_weight)} lb`;drawReport();renderHistory($('workoutHistoryList'),history);}
function drawReport(){renderChart($('progressChart'),$('chartMessage'),$('reportMetric').value,history,bodyWeights);}
async function resetData(){if(!confirm('Open reset options? Nothing will be erased yet.'))return;if(prompt('Type RESET to permanently erase your cloud fitness data.')!=='RESET')return alert('Nothing was erased.');if(!confirm('Final warning: erase all cloud workout and body-weight records?'))return;await deleteAllUserData(session.user.id);await route();}

route();
